[project]
name = "image-caption-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clearml>=2.1.2",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
]
